name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-msvc
